// Content for /services and every /services/[slug] page. Each entry is rendered by components/ServicePage.jsx.
// Rules for editing: describe only what CodeLaksh genuinely does, never invent clients, numbers or awards, and give
// pricing guidance only as "depends on scope" (no published price list exists).

export const services = [
  {
    slug: 'custom-software-development',
    icon: 'fa-laptop-code',
    name: 'Custom Software Development',
    anchor: 'Custom software development services',
    cardText:
      'Business software designed around your workflow: internal tools, customer portals, automation and integrations, built and maintained for you.',
    title: 'Custom Software Development Company in India | CodeLaksh',
    description:
      'CodeLaksh builds custom software for Indian businesses: internal tools, customer portals, automation and integrations, designed around how your team actually works.',
    h1: 'Custom Software Development Company in India',
    lead:
      'CodeLaksh designs and builds software around the way your business actually runs, from a single internal tool to a full multi-user platform.',
    intro: [
      'Off-the-shelf software works until your process stops fitting it. When your team keeps exporting to spreadsheets, repeating the same steps by hand or paying for features it never uses, a purpose-built application usually costs less over time than working around a generic one.',
      'CodeLaksh is a software development company based in Aurangabad (Chhatrapati Sambhajinagar), Maharashtra. Our team of developers, designers and project managers takes a project from requirement gathering to launch and support, and works with businesses across India. We also build and sell our own product, CodeLaksh ERP, so we know what it takes to keep software running for real customers after launch.',
    ],
    buildsTitle: 'What we build',
    builds: [
      ['Internal business applications', 'Order, inventory, HR, approvals and reporting tools that replace spreadsheets and chat-based coordination.'],
      ['Customer and partner portals', 'Secure logins where customers, dealers or vendors place requests, track status and download documents.'],
      ['Workflow automation', 'Rules, approvals, reminders and notifications that remove repeated manual steps between people and systems.'],
      ['Integrations and APIs', 'Connections between your software, payment gateways, accounting tools, WhatsApp or SMS providers and third-party services.'],
      ['Dashboards and reporting', 'Live views of sales, stock, collections or operations so decisions rest on current data.'],
      ['Modernising legacy tools', 'Moving an ageing desktop or spreadsheet-based system to a maintainable web or mobile application without losing your data.'],
    ],
    useCasesTitle: 'Where custom software helps',
    useCases: [
      'A distributor tracking orders, dispatches and payments across several people',
      'A clinic or service business managing appointments, records and billing in one place',
      'A manufacturer replacing paper job cards with a simple production tracker',
      'A growing company that needs role-based access and an audit trail for its staff',
      'A business that wants customers to self-serve instead of calling for every update',
    ],
    tech: [
      ['Web and back end', 'React, Next.js, Node.js, Python, TypeScript, REST APIs'],
      ['Mobile', 'Android, iOS and cross-platform apps'],
      ['Delivery', 'Cloud hosting on AWS, Azure or Google Cloud, with backups and monitoring'],
    ],
    benefits: [
      ['Fits your process', 'The software follows your workflow instead of forcing your team to change theirs.'],
      ['You own the roadmap', 'Features are prioritised by your business needs and released in stages you can review.'],
      ['Built to grow', 'Roles, branches, integrations and reports can be added as the business expands.'],
      ['Support after launch', 'We stay available for fixes, updates and new requirements once the system is live.'],
    ],
    faqs: [
      ['What does a custom software development company do?', 'A custom software development company designs, builds, tests, deploys and maintains software made for one organisation\'s specific needs, rather than selling the same package to everyone. That includes requirement analysis, design, development, integration with your existing tools, launch and ongoing support.'],
      ['How much does custom software development cost in India?', 'Cost depends on scope: the number of user roles, screens, integrations, reports and platforms. We do not publish a fixed price list. After a short discussion of your requirements we share a written estimate and, for larger projects, a phased plan so you can start with the most valuable part.'],
      ['How long does it take to build a business application?', 'A focused internal tool can often be ready in weeks, while a multi-role platform with integrations takes several months. We agree a milestone plan before development starts and share working builds along the way so timelines stay visible.'],
      ['Will I own the source code?', 'Ownership terms are agreed in the project contract before work begins. Tell us early if you need full source-code handover so we can write that into the agreement.'],
      ['Do you provide support after the software goes live?', 'Yes. We offer maintenance and support after launch, including bug fixes, updates and new features as your requirements change.'],
    ],
    related: ['web-development', 'mobile-app-development', 'erp-development', 'cloud-solutions'],
  },
  {
    slug: 'web-development',
    icon: 'fa-code',
    name: 'Web Development',
    anchor: 'Web development services',
    cardText:
      'Business websites, web applications, SaaS platforms, enterprise portals, dashboards and e-commerce stores built with modern web technology.',
    title: 'Web Development Company in India | CodeLaksh',
    description:
      'CodeLaksh is a web development company in Aurangabad building business websites, web apps, SaaS platforms, portals, dashboards and online stores across India.',
    h1: 'Web Development Company in India',
    lead:
      'From a fast business website to a multi-user web application, CodeLaksh builds web products that load quickly, work on every screen and can be found on Google.',
    intro: [
      'A website is often the first place a customer judges your business, and a web application is often where your team spends its day. Both need to be fast, secure and easy to maintain.',
      'CodeLaksh is a web development company in Aurangabad (Chhatrapati Sambhajinagar). We build with React, Next.js, Node.js and Python, and we care about the parts that are easy to skip: search-friendly page structure, mobile layouts, accessibility and clean deployment. This website is built the same way.',
    ],
    buildsTitle: 'Web projects we take on',
    builds: [
      ['Business websites', 'Clear, fast, mobile-friendly websites that explain what you do and make it easy for customers to contact you.'],
      ['Web applications', 'Browser-based tools with logins, roles, forms, workflows and reports for your team or your customers.'],
      ['SaaS platforms', 'Subscription-based products with accounts, plans, billing and an admin area.'],
      ['Enterprise portals', 'Secure portals for employees, dealers or vendors, connected to your existing systems.'],
      ['Dashboards', 'Charts and tables on live business data, with filters and exports.'],
      ['E-commerce platforms', 'Catalogues, carts, payments and order management for selling online. See our e-commerce development services.'],
    ],
    useCasesTitle: 'Typical use cases',
    useCases: [
      'A company website that needs to rank for its services and generate enquiries',
      'A customer portal for tracking orders, invoices or support requests',
      'An internal admin panel replacing spreadsheets',
      'A booking or registration system for a service business',
      'A software-as-a-service product being taken from idea to first users',
    ],
    tech: [
      ['Front end', 'React, Next.js, TypeScript, responsive HTML and CSS'],
      ['Back end', 'Node.js, Python, REST APIs'],
      ['Quality', 'Search-friendly rendering, accessibility basics, performance checks, secure forms'],
    ],
    benefits: [
      ['Built to be found', 'Pages are rendered so search engines can read titles, headings, text and links without waiting on scripts.'],
      ['Fast on mobile', 'We optimise images, fonts and scripts so pages load quickly on ordinary phone connections.'],
      ['Easy to maintain', 'Clean, documented code so future changes do not mean starting over.'],
      ['Secure by default', 'Validated forms, protected admin areas and sensible access control.'],
    ],
    faqs: [
      ['How long does it take to build a business website?', 'A typical business website takes a few weeks from content and design approval to launch. Web applications take longer depending on the number of roles, screens and integrations.'],
      ['Will my website appear on Google?', 'We build sites with search-friendly structure: unique titles, descriptions, headings, internal links, a sitemap and structured data. Ranking also depends on your content, competition and the authority your site earns over time, so no agency can honestly guarantee a position.'],
      ['Do you build web applications as well as websites?', 'Yes. We build web applications with user accounts, roles, dashboards, reports and integrations, as well as marketing websites.'],
      ['Can you redesign or rebuild my existing website?', 'Yes. We can redesign an existing site, keep the URLs that already earn traffic, and set up redirects so search visibility is not lost in the move.'],
      ['Do you provide hosting and maintenance?', 'We can deploy your site to cloud hosting and provide ongoing maintenance, updates and support.'],
    ],
    related: ['custom-software-development', 'ecommerce-development', 'digital-marketing', 'cloud-solutions'],
  },
  {
    slug: 'mobile-app-development',
    icon: 'fa-mobile-screen-button',
    name: 'Mobile App Development',
    anchor: 'Mobile app development services',
    cardText:
      'Android, iOS and cross-platform apps for businesses and customers, from business tools to e-commerce apps, including our own live apps.',
    title: 'Mobile App Development Company in India | CodeLaksh',
    description:
      'CodeLaksh is a mobile app development company in Aurangabad building Android, iOS and cross-platform apps: business apps, customer apps and e-commerce apps for India.',
    h1: 'Mobile App Development Company in India',
    lead:
      'CodeLaksh builds Android, iOS and cross-platform mobile apps for businesses that want to serve customers or run operations from a phone.',
    intro: [
      'Most customers in India reach a business first on their phone, and most owners want to check their numbers there too. A good app is quick to open, works on weak networks and does one job clearly.',
      'We have shipped apps ourselves: CodeLaksh ERP is live on Google Play, and Kidodom, our consumer app for parents, is available on the App Store and Google Play. That experience with store listings, releases, updates and real user feedback carries into client projects.',
    ],
    buildsTitle: 'Apps we build',
    builds: [
      ['Android applications', 'Apps for the widest phone audience in India, tested across common screen sizes and Android versions.'],
      ['iOS applications', 'Apps for iPhone and iPad with the interface conventions Apple users expect.'],
      ['Cross-platform applications', 'One shared codebase for Android and iOS when it fits your budget and feature set.'],
      ['Business applications', 'Billing, field-sales, attendance, order-taking and approval apps for your staff.'],
      ['Customer applications', 'Ordering, booking, loyalty and account apps that keep customers coming back.'],
      ['E-commerce applications', 'Catalogue, cart, payments and order tracking in a native-feeling shopping app.'],
    ],
    useCasesTitle: 'Where a mobile app makes sense',
    useCases: [
      'A retailer who wants customers to order and reorder from their phone',
      'A sales team that needs to take orders and collect payments on the road',
      'A business owner who wants daily sales and dues on a phone dashboard',
      'A service business offering bookings, reminders and receipts in an app',
      'A product company launching a consumer app on both app stores',
    ],
    tech: [
      ['Platforms', 'Android, iOS and cross-platform'],
      ['Integrations', 'Payment gateways such as Razorpay and PhonePe, push notifications, WhatsApp and SMS providers'],
      ['Release', 'Play Store and App Store submission, versioning and update management'],
    ],
    benefits: [
      ['Built for real phones', 'Layouts and performance tested on typical Android and iOS devices.'],
      ['Offline-aware', 'Where the use case needs it, apps keep working with weak connectivity and sync later.'],
      ['Store-ready', 'We handle listings, builds and submissions so the app reaches users.'],
      ['Connected to your systems', 'Apps share data with your web application or ERP rather than creating a separate silo.'],
    ],
    faqs: [
      ['Can CodeLaksh build Android and iOS applications?', 'Yes. We build Android apps, iOS apps and cross-platform apps that run on both. We recommend the approach after understanding your features, budget and timeline.'],
      ['Should I choose native or cross-platform?', 'Cross-platform suits most business and customer apps and reduces cost. Native development suits apps that depend heavily on device-specific features or maximum performance. We explain the trade-offs for your case before you decide.'],
      ['How long does it take to build a mobile app?', 'A focused app with a few core features can be built in a couple of months. Larger apps with accounts, payments and admin panels take longer. We agree milestones up front.'],
      ['Will you publish the app on the Play Store and App Store?', 'Yes. We prepare builds and store listings and support the submission, and you keep control of your developer accounts.'],
      ['Can the app connect to my existing software?', 'Yes. We build APIs and integrations so the app works with your website, ERP or accounting system.'],
    ],
    related: ['custom-software-development', 'ecommerce-development', 'erp-development', 'web-development'],
  },
  {
    slug: 'ai-development',
    icon: 'fa-robot',
    name: 'AI Development',
    anchor: 'AI development services',
    cardText:
      'AI-powered applications, chatbots trained on your own content, business automation, predictive analytics and AI integrations for existing software.',
    title: 'AI Development Company in India | CodeLaksh',
    description:
      'CodeLaksh is an AI development company in India building AI chatbots, AI-powered applications, business automation and intelligent dashboards, or adding AI to your software.',
    h1: 'AI Development Company in India',
    lead:
      'CodeLaksh builds practical AI solutions: chatbots that answer from your own information, automation that removes repetitive work, and AI features inside the software you already use.',
    intro: [
      'Most businesses do not need an AI research project. They need a specific job done faster: answering the same customer questions, reading documents, drafting replies, flagging unusual transactions or summarising reports.',
      'CodeLaksh builds AI into real business applications. We start from the problem and the data you have, choose the simplest approach that works, and put sensible limits around what the system may answer or do. Our machine learning development services cover custom models when a ready-made AI service is not enough.',
    ],
    buildsTitle: 'AI solutions we build',
    builds: [
      ['AI-powered applications', 'Applications where AI handles a core task such as search, classification, extraction or drafting.'],
      ['AI chatbots', 'Chatbots for your website or WhatsApp that answer from your own catalogue, policies and documents, with a handover path to your team.'],
      ['Business automation', 'Workflows that read, route and respond to emails, forms and documents without manual copying.'],
      ['Predictive analytics', 'Forecasts for demand, stock or collections drawn from your historical data.'],
      ['AI integrations', 'Adding AI features to an existing website, ERP or mobile app through APIs.'],
      ['Intelligent dashboards', 'Dashboards that explain what changed in plain language and highlight what needs attention.'],
    ],
    useCasesTitle: 'Common starting points',
    useCases: [
      'A support chatbot that answers product, pricing and order questions at any hour',
      'Reading invoices or forms and filling them into your system',
      'Summarising long reports or conversations for managers',
      'Searching your internal documents in plain language',
      'Flagging unusual sales, returns or expenses for review',
    ],
    tech: [
      ['Approach', 'Large language model APIs, retrieval over your own documents, rules and human review where accuracy matters'],
      ['Build', 'Python and Node.js services, web and mobile front ends'],
      ['Safeguards', 'Access control, logging, and clear limits on what the AI can answer or change'],
    ],
    benefits: [
      ['Starts with the problem', 'We pick a use case with a clear before and after, then expand once it works.'],
      ['Grounded in your data', 'Answers come from your content rather than generic web knowledge.'],
      ['Human in the loop', 'Sensitive actions stay under review, and the system hands over to your team when unsure.'],
      ['Fits what you run', 'AI is added to your existing application instead of replacing it.'],
    ],
    faqs: [
      ['Can CodeLaksh integrate AI into an existing application?', 'Yes. We can add AI features such as a chatbot, document reading, smart search or summaries to an existing website, web application, mobile app or ERP through APIs.'],
      ['What is an AI chatbot and what can it do for my business?', 'An AI chatbot understands questions in natural language and replies using information you provide, such as product details, policies and order status. It can handle common questions at any hour and pass complex ones to your team.'],
      ['Is my data safe when using AI?', 'We design access control and data handling with you, choose services that suit your confidentiality needs, and avoid sending data that does not need to leave your systems.'],
      ['How much does an AI project cost?', 'It depends on the use case, the amount of data and the integrations involved. We recommend starting with one well-defined use case and give a written estimate after understanding it.'],
      ['Do I need a lot of data to start?', 'Not always. Many useful AI features, such as chatbots and document reading, work from the content you already have. Predictive features need enough historical data, and we tell you honestly when yours is not enough.'],
    ],
    related: ['machine-learning', 'custom-software-development', 'web-development', 'cloud-solutions'],
  },
  {
    slug: 'machine-learning',
    icon: 'fa-brain',
    name: 'Machine Learning',
    anchor: 'Machine learning development services',
    cardText:
      'Custom machine learning models for prediction, classification and automation, delivered as working features inside your business software.',
    title: 'Machine Learning Development Company in India | CodeLaksh',
    description:
      'CodeLaksh develops custom machine learning models for prediction, classification and business automation, and delivers them as working features inside your software.',
    h1: 'Machine Learning Development Company in India',
    lead:
      'When a ready-made AI service is not enough, CodeLaksh develops custom machine learning models trained on your data and delivers them as features your team can use every day.',
    intro: [
      'Machine learning learns patterns from past data to make predictions on new data: which customers may stop buying, how much stock to order, which transactions look unusual. It is most useful when the question is clear, the data exists and a wrong answer is not catastrophic.',
      'CodeLaksh treats machine learning as an engineering project, not a demo. We check whether your data can support the question, build the simplest model that meets the need, measure it honestly against your own records, and connect it to an application so the result reaches the people who act on it.',
    ],
    buildsTitle: 'Machine learning work we do',
    builds: [
      ['Prediction and forecasting', 'Demand, sales, stock and cash-flow forecasts based on your history and seasonality.'],
      ['Classification', 'Sorting tickets, documents, leads or products into categories automatically.'],
      ['Anomaly detection', 'Spotting unusual transactions, returns or readings that deserve a second look.'],
      ['Recommendation', 'Suggesting products, reorder quantities or next actions from past behaviour.'],
      ['Data preparation', 'Cleaning and structuring scattered spreadsheets and database records so models can learn from them.'],
      ['Model deployment', 'Serving models through an API and connecting them to your web, mobile or ERP software.'],
    ],
    useCasesTitle: 'Where it fits',
    useCases: [
      'A retailer forecasting which items to reorder before they run out',
      'A distributor estimating which customers are likely to pay late',
      'A business classifying incoming support requests by topic and urgency',
      'A team that wants an early warning when sales or stock move unusually',
      'A company turning years of records into a forecast dashboard',
    ],
    tech: [
      ['Modelling', 'Python and common machine learning libraries'],
      ['Data', 'Your databases, spreadsheets and exports, cleaned and validated first'],
      ['Delivery', 'APIs and dashboards connected to your application, with monitoring after launch'],
    ],
    benefits: [
      ['Honest feasibility check', 'We tell you early if your data cannot support the question, before you invest in a model.'],
      ['Measured on your data', 'Accuracy is tested against your own historical records, not a generic benchmark.'],
      ['Usable, not a notebook', 'Results appear in an application or dashboard your team already opens.'],
      ['Maintained over time', 'Models are monitored and retrained as your business changes.'],
    ],
    faqs: [
      ['What is the difference between AI development and machine learning?', 'Machine learning is one part of AI: models that learn from your data to predict or classify. AI development is broader and includes chatbots and language features. Our AI development services cover applications and chatbots, while this service is for custom models.'],
      ['How much data do I need for machine learning?', 'It depends on the question. Forecasting usually needs a year or more of consistent records. We review your data first and tell you honestly whether it is enough.'],
      ['How accurate will the model be?', 'We do not promise a figure up front. We test the model on your historical data, share the results and agree what level is useful before it goes live.'],
      ['Can you add machine learning to my existing software?', 'Yes. We deploy models behind an API and connect them to your existing web application, mobile app or ERP.'],
      ['How long does a machine learning project take?', 'A first working model on clean data can take a few weeks. Data preparation and integration often take longer than the modelling itself, and we plan for that.'],
    ],
    related: ['ai-development', 'erp-development', 'custom-software-development', 'cloud-solutions'],
  },
  {
    slug: 'erp-development',
    icon: 'fa-boxes-stacked',
    name: 'ERP & Business Software',
    anchor: 'ERP development services',
    cardText:
      'ERP and business software for billing, inventory, accounting, purchases and payments, including our own product CodeLaksh ERP live on Google Play.',
    title: 'Custom ERP Development Company in India | CodeLaksh',
    description:
      'CodeLaksh develops ERP and business software for Indian companies: GST billing, inventory, accounting and payments. See CodeLaksh ERP, live on Google Play.',
    h1: 'Custom ERP Development Company in India',
    lead:
      'CodeLaksh builds ERP and business software for Indian businesses, and runs its own product, CodeLaksh ERP, for billing, inventory, accounting and payments.',
    intro: [
      'An ERP brings billing, stock, purchases, accounts and reports into one system so everyone works from the same numbers. For Indian businesses it also has to handle GST invoices, party ledgers, barcodes and counters that must keep billing when the internet drops.',
      'CodeLaksh is not only a development agency for ERP projects. We design, ship and support CodeLaksh ERP, which has a Windows desktop app that works offline, an Android app on Google Play, cloud sync, multi-branch support, role-based access and modules for different kinds of business. We use that product experience when we build custom ERP and business software for clients.',
    ],
    buildsTitle: 'What our ERP and business software covers',
    builds: [
      ['Billing and GST invoicing', 'GST-ready invoices with CGST and SGST, barcode scanning, printing, PDF and sharing.'],
      ['Inventory and purchases', 'Stock levels, batches and expiry, purchase bills, supplier ledgers and low-stock alerts.'],
      ['Accounting', 'Cash and bank books, journal, trial balance, income statement and balance sheet.'],
      ['Multi-branch and roles', 'Several outlets under one account, stock transfers, custom roles and approval flows.'],
      ['Payments and e-bills', 'Online payments through Razorpay or PhonePe and invoices sent by email or WhatsApp.'],
      ['Industry modules', 'Restaurant, hotel, kirana, sweet mart, bakery, medical store, salon and more. See the CodeLaksh ERP plans.'],
    ],
    useCasesTitle: 'Businesses that use this kind of software',
    useCases: [
      'Retail shops, supermarkets and kirana stores billing at a busy counter',
      'Restaurants, cafes and hotels managing tables, kitchen orders and rooms',
      'Medical stores tracking batches and expiry dates',
      'Distributors with multiple branches and a supplier ledger',
      'Businesses moving off Tally, Vyapar or manual books and needing their data migrated',
    ],
    tech: [
      ['Applications', 'Windows desktop app, Android app and web access'],
      ['Platform', 'Offline-first billing with cloud sync and backup'],
      ['Languages', 'English, Hindi, Marathi and Gujarati interface'],
    ],
    benefits: [
      ['One set of numbers', 'Sales, stock and accounts update together instead of living in separate tools.'],
      ['Keeps billing offline', 'The desktop app works at the counter without internet and syncs when it returns.'],
      ['Proven in production', 'CodeLaksh ERP is a live product with published plans, so you can see how it works before committing.'],
      ['Customisation on request', 'If an existing module does not fit, we can extend it or build custom business software around it.'],
    ],
    faqs: [
      ['Does CodeLaksh develop ERP software?', 'Yes. We develop and sell CodeLaksh ERP, and we build custom ERP and business software for companies whose workflow does not fit a standard product.'],
      ['Should I use CodeLaksh ERP or get a custom ERP built?', 'If your needs are billing, inventory, accounting and payments for a retail, restaurant, hotel or similar business, CodeLaksh ERP is usually the faster and more economical route. If you have unusual workflows or need deep integration with other systems, a custom build or an extension makes sense. We will tell you which one fits.'],
      ['Can you move my data from Tally, Vyapar or manual books?', 'Yes. Data migration and onboarding is offered as an add-on for CodeLaksh ERP, and it is covered in our ERP pricing.'],
      ['Does the ERP support GST?', 'Yes. Invoices are GST-ready with CGST and SGST, and GST, sales, purchase and stock reports are included.'],
      ['How much does a custom ERP cost?', 'It depends on modules, users, branches and integrations. For standard needs, published CodeLaksh ERP plans start at Rs. 3,499 per year excluding GST. For custom work we share a written estimate after reviewing requirements.'],
    ],
    related: ['custom-software-development', 'mobile-app-development', 'cloud-solutions', 'ai-development'],
    extraLink: { href: '/erp', label: 'See CodeLaksh ERP features and pricing' },
  },
  {
    slug: 'ecommerce-development',
    icon: 'fa-cart-shopping',
    name: 'E-Commerce Development',
    anchor: 'E-commerce development services',
    cardText:
      'Online stores and shopping apps with catalogues, carts, payments and order management, for Indian customers and sellers.',
    title: 'E-Commerce Development Company in India | CodeLaksh',
    description:
      'CodeLaksh builds e-commerce websites and shopping apps for Indian businesses: catalogues, carts, UPI and card payments, order management and inventory connections.',
    h1: 'E-Commerce Development Company in India',
    lead:
      'CodeLaksh builds online stores and shopping apps that are simple for customers to buy from and simple for your team to run.',
    intro: [
      'Selling online in India means more than a product page. Customers expect UPI and card payments, clear delivery information, WhatsApp updates and a checkout that works on a mid-range phone. Your team needs to manage stock, orders and returns without double entry.',
      'We build e-commerce as part of the same engineering practice that produces our other software. Our own Kidodom app, a shopping and parenting app on the App Store and Google Play, gave us first-hand experience of building product catalogues, sign-in, deals and a mobile shopping flow.',
    ],
    buildsTitle: 'E-commerce projects we build',
    builds: [
      ['Online stores', 'Catalogues with categories, search, variants, carts and checkout.'],
      ['Shopping apps', 'Android and iOS apps with the same catalogue and orders as your website.'],
      ['Payments', 'Razorpay, PhonePe and other gateways, with receipts and reconciliation.'],
      ['Order management', 'Order status, invoices, dispatch details and returns handled from one admin panel.'],
      ['Inventory connection', 'Stock levels shared with your billing system or ERP to avoid overselling.'],
      ['Offers and loyalty', 'Coupons, deals and repeat-purchase features that fit your products.'],
    ],
    useCasesTitle: 'Typical e-commerce cases',
    useCases: [
      'A local retailer adding an online store alongside the shop',
      'A brand launching a shopping app for repeat customers',
      'A distributor offering online ordering to its retailers',
      'A business whose website orders must update stock in its billing software',
      'A store that wants WhatsApp order updates for customers',
    ],
    tech: [
      ['Storefront', 'React, Next.js, responsive design, search-friendly product pages'],
      ['Payments', 'Razorpay, PhonePe and other gateways'],
      ['Connections', 'Inventory, accounting, WhatsApp and SMS providers'],
    ],
    benefits: [
      ['Mobile-first checkout', 'Designed for phone buyers, with few steps and clear payment options.'],
      ['Search-friendly products', 'Product and category pages are readable by search engines so shoppers can find them.'],
      ['One stock count', 'Online and in-store sales draw from the same inventory.'],
      ['Easy admin', 'Your team can add products, change prices and process orders without a developer.'],
    ],
    faqs: [
      ['Do you build e-commerce apps as well as websites?', 'Yes. We build online stores for the web and shopping apps for Android and iOS that share one catalogue and one set of orders.'],
      ['Which payment methods can the store accept?', 'We integrate Indian payment gateways such as Razorpay and PhonePe, which cover UPI, cards and net banking. The exact methods depend on the gateway account you hold.'],
      ['Can the online store connect to my billing or ERP software?', 'Yes. We can connect stock and orders with CodeLaksh ERP or other systems so online and in-store sales stay in sync.'],
      ['How long does an e-commerce project take?', 'A store with a standard catalogue and checkout can take a few weeks to a couple of months. Custom features, large catalogues and app development add time, and we agree a plan before starting.'],
      ['Will my products appear on Google?', 'We build product pages with search-friendly titles, descriptions and structured data. Rankings also depend on content, competition and time, so we cannot promise positions.'],
    ],
    related: ['web-development', 'mobile-app-development', 'erp-development', 'digital-marketing'],
  },
  {
    slug: 'cloud-solutions',
    icon: 'fa-cloud',
    name: 'Cloud Solutions',
    anchor: 'Cloud solutions',
    cardText:
      'Cloud architecture, migration and deployment on AWS, Azure and Google Cloud, with backups, monitoring and secure infrastructure for your applications.',
    title: 'Cloud Solutions Company in India | CodeLaksh',
    description:
      'CodeLaksh designs cloud architecture, migration and deployment on AWS, Azure and Google Cloud, so your applications run securely with backups and monitoring.',
    h1: 'Cloud Solutions Company in India',
    lead:
      'CodeLaksh helps businesses run their applications on AWS, Azure or Google Cloud: planned properly, deployed cleanly and monitored after launch.',
    intro: [
      'Moving to the cloud is not only about renting servers. The decisions that matter are which services to use, how data is backed up, who can access what, what happens when traffic spikes and what the monthly bill will look like.',
      'We design and operate the infrastructure behind the software we build, including cloud sync and backup for CodeLaksh ERP. For clients, we apply the same discipline: a simple architecture that fits the workload, documented access, and costs you can predict.',
    ],
    buildsTitle: 'Cloud services we provide',
    builds: [
      ['Cloud architecture', 'A design for hosting your application, database, storage and background jobs on the right services.'],
      ['Cloud migration', 'Moving applications and data from an office server or shared hosting to the cloud with planned cut-over.'],
      ['Cloud deployment', 'Repeatable deployments for web applications and APIs, with staging and production environments.'],
      ['AWS, Azure and Google Cloud', 'We work with the three major providers and recommend one based on your needs and budget.'],
      ['Application infrastructure', 'Databases, file storage, queues, domains and SSL set up and documented.'],
      ['Backup and monitoring', 'Automated backups, uptime checks and alerts so problems are seen before customers report them.'],
    ],
    useCasesTitle: 'When to talk to us',
    useCases: [
      'Your application runs on a single office machine or ageing shared hosting',
      'You want your software available securely from any branch or device',
      'Your site slows down when many users arrive at once',
      'You need backups and a recovery plan you can actually test',
      'Cloud costs have grown and nobody is sure why',
    ],
    tech: [
      ['Providers', 'AWS, Microsoft Azure, Google Cloud'],
      ['Practices', 'Environments for staging and production, SSL, backups, access control, monitoring'],
      ['Applications', 'Web apps, APIs, databases and file storage'],
    ],
    benefits: [
      ['Predictable costs', 'We size the setup to the workload and explain the expected monthly spend.'],
      ['Safer data', 'Backups, encryption and restricted access are part of the design, not an afterthought.'],
      ['Less downtime', 'Monitoring and alerts catch problems early.'],
      ['Room to scale', 'Capacity can grow with traffic without rebuilding the application.'],
    ],
    faqs: [
      ['Which cloud provider should I choose?', 'It depends on your application, existing tools and budget. We work with AWS, Azure and Google Cloud and recommend one after reviewing your requirements.'],
      ['Can you migrate my existing application to the cloud?', 'Yes. We plan the migration, move the application and data, test it, and cut over with minimal downtime.'],
      ['Do you handle backups and monitoring?', 'Yes. Automated backups, uptime monitoring and alerts can be part of the setup and ongoing support.'],
      ['How much will cloud hosting cost?', 'Cost depends on traffic, storage and the services used. We estimate it during planning and review it after launch.'],
      ['Is cloud hosting secure?', 'Cloud platforms offer strong security tools, but safety depends on configuration. We set up access control, encryption and backups deliberately and document them.'],
    ],
    related: ['custom-software-development', 'web-development', 'erp-development', 'ai-development'],
  },
  {
    slug: 'digital-marketing',
    icon: 'fa-chart-line',
    name: 'Digital Marketing',
    anchor: 'Digital marketing services',
    cardText:
      'SEO, search visibility, social media and performance marketing that help the right customers find your business online.',
    title: 'Digital Marketing Company in India | CodeLaksh',
    description:
      'CodeLaksh offers digital marketing in India: SEO and search visibility, social media and performance marketing, joined with the website work that makes them effective.',
    h1: 'Digital Marketing Company in India',
    lead:
      'CodeLaksh helps businesses get found online through SEO, social media and paid campaigns, supported by a website that is built to convert visitors into enquiries.',
    intro: [
      'Marketing works best when the website behind it is fast, clear and easy to find. Because we build websites and software ourselves, we can fix technical problems that slow marketing down, such as slow pages, missing metadata or broken tracking, instead of only reporting them.',
      'We keep the promises realistic. Nobody can guarantee a number-one ranking or a fixed number of leads. What we do is improve the things you control: your site, your content, your listings and your campaigns, and measure the results openly.',
    ],
    buildsTitle: 'Marketing services',
    builds: [
      ['SEO and search visibility', 'Technical SEO, on-page optimisation, content planning and structured data so search engines understand your business.'],
      ['Local search presence', 'A consistent business profile, location information and listings that help nearby customers find you.'],
      ['Social media', 'Planning, content and posting that suit your audience and brand.'],
      ['Performance marketing', 'Search and social ad campaigns with clear targets, tracking and reporting.'],
      ['Website conversion', 'Landing pages, contact forms and calls to action that turn visits into enquiries.'],
      ['Analytics and reporting', 'Tracking set up properly, with regular reports in plain language.'],
    ],
    useCasesTitle: 'Where this helps',
    useCases: [
      'A business whose website exists but does not appear in Google searches',
      'A company launching a new product or app and needing early users',
      'A local business that wants more enquiries from its own city',
      'A team running ads without clear tracking of what works',
      'A brand that wants a consistent, active social presence',
    ],
    tech: [
      ['Search', 'Technical SEO audits, sitemaps, structured data, Google Search Console'],
      ['Campaigns', 'Google and social advertising platforms'],
      ['Measurement', 'Analytics and conversion tracking'],
    ],
    benefits: [
      ['Technical fixes included', 'Because we develop websites, we can fix what holds your visibility back.'],
      ['Honest expectations', 'We explain what is within our control and what depends on competition and time.'],
      ['Clear reporting', 'You see what was done, what moved and what is next.'],
      ['Built for growth', 'Marketing and product work together rather than in separate silos.'],
    ],
    faqs: [
      ['How long does SEO take to show results?', 'Technical fixes can be picked up within weeks, but meaningful gains in rankings usually take several months and depend on competition, content quality and the authority your site earns.'],
      ['Can you guarantee a first-page ranking?', 'No. Anyone guaranteeing a specific ranking is making a promise search engines do not allow. We work on the factors that are in your control and report progress honestly.'],
      ['Do you also build or fix the website?', 'Yes. Our development team can fix technical SEO issues, speed up pages and add new pages and content, which is often the fastest way to improve visibility.'],
      ['Do you manage paid campaigns?', 'Yes. We plan, run and report on search and social advertising campaigns with agreed goals and tracking.'],
      ['How much does digital marketing cost?', 'It depends on the channels, the scope and the monthly effort. We share a written proposal after understanding your goals and market.'],
    ],
    related: ['web-development', 'ecommerce-development', 'custom-software-development', 'ai-development'],
  },
];

export const getService = (slug) => services.find((service) => service.slug === slug);
