"""Source of truth for the 30-day plan (2 posts/day). `python3 tools/build.py` renders media + rewrites queue.json.
Every claim comes from the CodeLaksh website source (see README "Facts"). Prices exclude 18% GST.
Fields: id -> (pillar, hook, sub, body, shot, link_path, cta, draft_reason)
draft_reason set => stays `draft` until a human confirms the date/claim."""
ERP = "codelaksh.in/erp"
HOME = "codelaksh.in"
SVC = "codelaksh.in"
CON = "codelaksh.in"
KID = "kidodom.in"

TAGS = {
 "product-demo": "#GSTBilling #BillingSoftware #ERPSoftware #SmallBusinessIndia #CodeLaksh",
 "education": "#BusinessTips #SmallBusinessIndia #GSTIndia #BillingSoftware #CodeLaksh",
 "workflow-compare": "#BillingSoftware #BusinessAutomation #SmallBusinessIndia #ERPSoftware #CodeLaksh",
 "industry-problem": "#RestaurantBusiness #RetailIndia #BillingSoftware #SmallBusinessIndia #CodeLaksh",
 "showcase": "#SoftwareDevelopment #WebDevelopment #AppDevelopment #MadeInIndia #CodeLaksh",
 "faq": "#BillingSoftware #GSTBilling #SmallBusinessIndia #ERPSoftware #CodeLaksh",
 "ai-trends": "#AIforBusiness #Chatbot #MachineLearning #BusinessAutomation #CodeLaksh",
 "brand-story": "#CodeLaksh #SoftwareCompany #MadeInIndia #Aurangabad #Tech",
 "festival": "#FestiveSeason #SmallBusinessIndia #RetailIndia #BillingSoftware #CodeLaksh",
 "lead-cta": "#FreeTrial #BillingSoftware #SmallBusinessIndia #ERPSoftware #CodeLaksh",
 "kidodom": "#Kidodom #Parenting #BabyProducts #MadeInIndia #CodeLaksh",
}
LABEL = {"product-demo": "PRODUCT", "education": "LEARN", "workflow-compare": "BEFORE / AFTER", "industry-problem": "FOR YOUR BUSINESS",
         "showcase": "WHAT WE BUILD", "faq": "FAQ", "ai-trends": "AI & TECH", "brand-story": "ABOUT US", "festival": "FESTIVE SEASON",
         "lead-cta": "TRY IT", "kidodom": "KIDODOM"}

P = {
"2026-10-12-1": ("workflow-compare","Paper bill book or ERP invoice?","Same customer. Same items. Different effort.",
  "Writing every bill by hand means adding up totals, working out GST and re-copying for records.\n\nWith CodeLaksh ERP you pick the items (or scan the barcode), the GST invoice is ready, and you can print it, save a PDF or share it.\n\nLess re-writing at the counter, fewer arithmetic slips.", "inv", ERP, "See how invoicing works", None),
"2026-10-12-2": ("festival","Festive rush is coming. Is your counter ready?","Navratri wishes from CodeLaksh",
  "Wishing everyone a joyful Navratri from all of us at CodeLaksh.\n\nFestive weeks bring the busiest days at the counter. Fast, accurate GST billing and live stock levels help you serve every customer in the queue.\n\nTell us: what is the busiest day at your shop?", None, ERP, "Explore CodeLaksh ERP", "Confirm Navratri dates before approving"),
"2026-10-13-1": ("industry-problem","KOT chaos at 9 pm, or one screen for every table?","Restaurant billing, simplified",
  "When orders are taken on paper and shouted to the kitchen, mistakes happen at the busiest hour.\n\nThe Restaurant / Hotel Pro plan of CodeLaksh ERP adds KOT, table management, QR ordering and reservations on top of billing and inventory.\n\nRs. 1,999 per month per outlet (excludes 18% GST).", "mtab", ERP, "See the restaurant plan", None),
"2026-10-13-2": ("education","Is your invoice GST-ready? Check these.","A quick checklist",
  "A GST invoice should clearly show:\n- Your business name and GSTIN\n- Invoice number and date\n- Customer details where required\n- Item description, quantity and rate\n- Tax split (CGST / SGST) and the total\n\nRequirements can vary by case, so confirm specifics with your CA.\n\nCodeLaksh ERP prepares GST-ready invoices with the CGST / SGST split, and lets you print, download a PDF or share.", "inv", ERP, "See GST invoicing", None),
"2026-10-14-1": ("kidodom","We also build our own products. Meet Kidodom.","A CodeLaksh brand",
  "Kidodom is our baby and kids brand: products for feeding, clothing, toys and health, plus parenting tips and vaccine reminders.\n\nShop on the web or in the app, now on both the App Store and Google Play.", "k3", KID, "Visit kidodom.in", None),
"2026-10-14-2": ("faq","Can I try it before paying?","Yes, for 7 days",
  "CodeLaksh ERP's Starter and Growth plans both come with a 7-day free trial.\n\nStarter: Rs. 3,500 one-time (+ Rs. 1,499 per year renewal), one counter, works offline.\nGrowth: Rs. 599 per month, with cloud sync, mobile app and accounting.\n\nPrices exclude 18% GST.", "plan", ERP, "Start your free trial", None),
"2026-10-15-1": ("product-demo","From product list to printed barcode labels.","One screen, ready-to-print sheets",
  "Labelling products one by one is slow.\n\nIn CodeLaksh ERP you can build and print whole sheets of product barcode labels, then scan them at the counter during billing.", "bar", ERP, "Explore ERP features", None),
"2026-10-15-2": ("ai-trends","Your customers ask the same questions all day.","Let a chatbot answer the repeat ones",
  "An AI chatbot trained on your own FAQs can answer common questions (timings, services, pricing basics) at any hour and hand the harder ones to your team.\n\nWhat it won't do: replace your judgment on complex or sensitive cases. Good bots know when to pass the conversation to a human.\n\nCodeLaksh builds AI chatbots trained on your data for customer support.", None, SVC, "Talk to us about a chatbot", None),
"2026-10-16-1": ("education","Three reports that show if your shop is healthy.","Read these every week",
  "1. Sales report: what sold, and when.\n2. Stock report: what is running low and what is sitting unsold.\n3. Dues report: who owes you money.\n\nCodeLaksh ERP includes sales, purchase, stock and tax reports, with CSV export for your CA.", "rep", ERP, "See the reports", None),
"2026-10-16-2": ("brand-story","Who builds CodeLaksh?","Developers, designers, project managers",
  "CodeLaksh is a team of software developers, designers and project managers based in Aurangabad, building since 2020.\n\nWe make CodeLaksh ERP for Indian shops, restaurants and hotels, build custom websites, apps and AI solutions for businesses, and run our own brand, Kidodom.", None, HOME, "Say hello", None),
"2026-10-17-1": ("workflow-compare","Stock-outs stay invisible until a customer asks.","Register vs inventory system",
  "A paper stock register shows what you wrote down, not what is actually on the shelf today.\n\nCodeLaksh ERP tracks stock levels, batches and expiry, and raises low-stock alerts so you reorder before you run out.", "dash", ERP, "Explore inventory features", None),
"2026-10-17-2": ("faq","Stuck on old software? Your data can come with you.","Migration from Tally, Vyapar or manual books",
  "Moving to new software shouldn't mean typing everything again.\n\nCodeLaksh offers a data migration and onboarding add-on (Rs. 2,999 one-time, excludes 18% GST) to move your data from Tally, Vyapar or manual books.", None, ERP, "Ask us about migration", None),
"2026-10-18-1": ("industry-problem","Why does your billing queue move slowly?","Barcode scanning at the counter",
  "Searching for items by name and typing prices makes every customer wait.\n\nWith barcode scanning in CodeLaksh ERP, one scan adds the correct item to the bill and the GST invoice is ready for print or share.", "bar", ERP, "See barcode billing", None),
"2026-10-18-2": ("product-demo","Your shop's numbers, in your pocket.","The CodeLaksh ERP Android app",
  "Check revenue, dues and reports, track invoices and see payment status from your phone.\n\nCloud sync and the mobile app come with the Growth plan (Rs. 599 per month, excludes 18% GST). The Android app is live on Google Play.", "mbill", ERP, "Get the app", None),
"2026-10-19-1": ("education","Cash book, bank book, ledger: what's the difference?","Plain-language explainer",
  "Cash book: every rupee that moves in and out in cash.\nBank book: the same for your bank account.\nLedger: the running account of one customer or supplier, showing what they owe you or you owe them.\n\nCodeLaksh ERP's Growth plan keeps cash and bank books, purchases and the supplier ledger together.", "dash", ERP, "Explore accounting", None),
"2026-10-19-2": ("ai-trends","Stop doing these 3 tasks by hand.","Small automations, real time saved",
  "1. Sharing invoices: send a PDF or share link instead of retyping.\n2. Payment follow-ups: track dues in one place.\n3. Weekly reports: let software compile them.\n\nAutomation doesn't have to be big. Start with the task you repeat the most.\n\nWe build business automation and AI solutions. Tell us your repeat task.", None, SVC, "Tell us your repeat task", None),
"2026-10-20-1": ("festival","This Dussehra, retire the paper bill book.","Wishing you a happy Dussehra",
  "Happy Dussehra from CodeLaksh.\n\nThe festival of good over evil is a nice moment to retire one old habit. For many shops, that is the paper bill book.\n\nWhat habit are you leaving behind this year?", None, ERP, "Explore CodeLaksh ERP", "Confirm Dussehra date before approving"),
"2026-10-20-2": ("faq","What does billing software really cost?","CodeLaksh ERP plans (excl. 18% GST)",
  "Starter: Rs. 3,500 one-time + Rs. 1,499 per year renewal\nGrowth: Rs. 599 per month (or Rs. 5,999 per year)\nRestaurant / Hotel Pro: Rs. 1,999 per month per outlet\nEnterprise: from Rs. 4,999 per month\n\nStarter and Growth include a 7-day free trial.", "plan", ERP, "Compare plans", None),
"2026-10-21-1": ("workflow-compare","Chasing payments by phone, or sharing one receipt?","Collect payments faster",
  "Phone calls and reminders cost time and goodwill.\n\nOn the Growth plan, CodeLaksh ERP supports online payments through Razorpay or PhonePe, and you can share invoices and receipts instantly.", "mpay", ERP, "See payments in ERP", None),
"2026-10-21-2": ("showcase","Your website is your 24/7 salesperson. Is it working?","Web development by CodeLaksh",
  "We build modern, responsive websites and web applications with React, Node.js and Python, designed to load fast and be found.\n\nIf your site is slow, dated or hard to use on a phone, let's talk.", None, SVC, "Start a project", None),
"2026-10-22-1": ("industry-problem","Reservations in a diary, bills in Excel?","For hotels and restaurants",
  "When bookings, billing and stock live in different places, someone ends up re-entering the same data.\n\nThe Restaurant / Hotel Pro plan combines billing, inventory, table management, QR ordering and reservations in one system.", "mtab", ERP, "See the plan", None),
"2026-10-22-2": ("education","Filing week is easier if your books are ready.","A prep checklist",
  "Before you file:\n- Sales and purchase invoices recorded\n- Stock and expenses reconciled\n- Cash and bank books matched\n- Reports exported for your CA\n\nAlways confirm current due dates with your CA or the official GST portal.\n\nCodeLaksh ERP includes GST, sales, purchase and stock reports with CSV export.", "rep", ERP, "See the reports", "Confirm GST filing guidance and dates before approving"),
"2026-10-23-1": ("product-demo","Open the app. Know where your business stands.","Dashboard overview",
  "Revenue, dues, cash and bank balances on one screen, plus quick actions to create an invoice or add a customer.\n\nThat is the CodeLaksh ERP dashboard.", "dash", ERP, "Explore features", None),
"2026-10-23-2": ("brand-story","We build what your business actually needs.","Code Your Vision With Innovation",
  "Our line is \"Code Your Vision With Innovation\", and we mean it practically: listen first, then build software around your workflow and goals.\n\nWhether it's a website, an app, an AI chatbot or an ERP, we start with your problem, not our template.", None, CON, "Tell us your idea", None),
"2026-10-24-1": ("faq","Internet down. Can you still bill?","Offline billing on desktop",
  "Yes. The CodeLaksh ERP desktop app works fully offline at the counter.\n\nCloud sync and the mobile app are part of the Growth plan and above, so your numbers update on your other devices when you're back online.", "dash", ERP, "Learn how it works", None),
"2026-10-24-2": ("ai-trends","Machine learning isn't only for big companies.","In plain language",
  "Prediction: estimate what will sell next month.\nClassification: sort enquiries or documents automatically.\nAutomation: let a model handle repetitive decisions.\n\nA custom model needs good data and a clear question. We build custom ML models for prediction, classification and business automation.", None, SVC, "Discuss your use case", None),
"2026-10-25-1": ("workflow-compare","Month-end shouldn't take three days.","Manual totals vs automatic reports",
  "Adding up registers and Excel sheets at month-end is slow and easy to get wrong.\n\nCodeLaksh ERP's Growth plan keeps books as you work, with profit and loss and balance sheet reports ready when you need them.", "rep", ERP, "Explore accounting", None),
"2026-10-25-2": ("industry-problem","Where did that stock go?","For distributors",
  "Purchases in one place, supplier payments in another, stock counts somewhere else: the numbers rarely agree.\n\nCodeLaksh ERP connects purchases, the supplier ledger and inventory so you can trace the difference.", "dash", ERP, "Explore features", None),
"2026-10-26-1": ("education","One scan, one correct item.","Barcode basics",
  "Barcodes replace typing. Each product gets a unique code, a scan finds the product, and the price and tax come from the product record.\n\nResult: fewer entry mistakes at the counter. CodeLaksh ERP supports barcode scanning and label printing.", "bar", ERP, "Explore features", None),
"2026-10-26-2": ("festival","Festive season is peak billing season.","Retail tips for the rush",
  "Three things to check before the rush:\n1. Stock levels of your fastest sellers.\n2. Counter speed: barcode labels on every item.\n3. Backup plan: billing that doesn't stop when the internet does.\n\nWishing all retailers a busy, profitable festive season.", None, ERP, "Try CodeLaksh ERP free for 7 days", "Confirm festival date before approving"),
"2026-10-27-1": ("showcase","Have an app idea? Here's how we build.","Mobile app development",
  "We design and build native and cross-platform apps for Android and iOS, from UI/UX to launch.\n\nWe also build our own: CodeLaksh ERP is live on Google Play, and Kidodom is on the App Store and Google Play.", "k2", SVC, "Start your app project", None),
"2026-10-27-2": ("faq","Is ERP built for restaurants too?","Yes: Restaurant / Hotel Pro",
  "The Restaurant / Hotel Pro plan adds KOT, table management, QR ordering and reservations on top of billing and inventory.\n\nRs. 1,999 per month per outlet, 2 branches or counters included (excludes 18% GST).", "mtab", ERP, "See the plan", None),
"2026-10-28-1": ("product-demo","Create. Download. Share. Done.","The invoice flow",
  "Build the invoice, then print it, download a PDF or share it with the customer.\n\nSimple, fast and GST-ready, with the CGST / SGST split built in.", "inv", ERP, "See invoicing", None),
"2026-10-28-2": ("education","Five signs Excel is slowing your business.","Time to move on?",
  "1. Totals break when someone edits a cell.\n2. Stock and billing never match.\n3. Only one person can use the file at a time.\n4. You can't bill without opening a spreadsheet.\n5. Reports take hours to build.\n\nIf you nodded at two or more, it may be time for billing software.", None, ERP, "Try ERP free for 7 days", None),
"2026-10-29-1": ("ai-trends","What if your website answered customers at 2 am?","AI chatbots for support",
  "Customers browse at night. A chatbot trained on your own information can answer common questions any time and pass complex ones to your team.\n\nWe build AI chatbots for 24/7 customer support.", None, SVC, "Ask for a chatbot demo", None),
"2026-10-29-2": ("workflow-compare","Notebook entry, or one search?","Customer and supplier records",
  "Flipping through pages to find one customer's balance wastes time at the counter.\n\nCodeLaksh ERP keeps customer and supplier records in one place, with the supplier ledger on the Growth plan.", "mbill", ERP, "Explore features", None),
"2026-10-30-1": ("industry-problem","Expired stock is money lost.","For medical stores and shops with expiry dates",
  "Tracking expiry on paper is hard to keep up with.\n\nCodeLaksh ERP tracks stock by batch and expiry, and low-stock alerts help you reorder in time.", "dash", ERP, "See inventory features", None),
"2026-10-30-2": ("brand-story","How we build features.","Our process, simply",
  "1. Listen to the problem.\n2. Design the simplest solution.\n3. Build and test it.\n4. Release it and listen again.\n\nThe same loop shapes CodeLaksh ERP and the custom software we build for clients.", None, HOME, "Follow for more", None),
"2026-10-31-1": ("faq","Is there a mobile app? Yes.","CodeLaksh ERP on Android",
  "The CodeLaksh ERP Android app is live on Google Play. Bill, track invoices and view reports from your phone.\n\nCloud sync and the mobile app come with the Growth plan.", "mbill", ERP, "Get it on Google Play", None),
"2026-10-31-2": ("education","Why do staff avoid your software?","3 UI/UX mistakes",
  "1. Too many steps for a common task.\n2. Labels only the developer understands.\n3. No clear next action on each screen.\n\nGood UI/UX makes software feel obvious. We design user-centred interfaces that make products intuitive.", None, SVC, "Talk to our design team", None),
"2026-11-01-1": ("festival","Diwali week checklist for shopkeepers.","Be ready before the rush",
  "- Stock: count and reorder your top sellers\n- Billing: test your counter setup and printer\n- Labels: barcode labels on new stock\n- Staff: agree roles for the busy days\n- Records: keep invoices and books up to date\n\nSave this post for your festive prep.", None, ERP, "Explore CodeLaksh ERP", "Confirm Dhanteras/Diwali dates before approving"),
"2026-11-01-2": ("product-demo","Every table, one glance.","Table management",
  "See which tables are free, occupied or waiting, in real time on your phone.\n\nPart of the Restaurant / Hotel Pro plan in CodeLaksh ERP.", "mtab", ERP, "See restaurant features", None),
"2026-11-02-1": ("workflow-compare","Busy-day billing: two ways.","Slow vs scan-and-bill",
  "Way 1: write each item, add up totals by hand, queue builds.\nWay 2: scan, review, print or share the GST invoice.\n\nChoose the one that lets you serve the next customer faster.", "bar", ERP, "Try ERP free for 7 days", None),
"2026-11-02-2": ("faq","Which plan fits your business?","Starter, Growth, Pro, Enterprise",
  "Starter: one counter, works offline.\nGrowth: cloud sync, mobile app and accounting.\nRestaurant / Hotel Pro: KOT, tables, QR ordering, reservations.\nEnterprise: multi-branch and custom needs, from Rs. 4,999 per month.\n\nAll prices exclude 18% GST.", "plan", ERP, "Compare plans", None),
"2026-11-03-1": ("kidodom","One app for everything your little one needs.","Kidodom app tour",
  "Shop for feeding, clothing, toys and health, use the guidance hub with a vaccination tracker and developmental milestones, and keep an eye on deals for parents.\n\nKidodom is on the App Store and Google Play.", "k5", KID, "Visit kidodom.in", None),
"2026-11-03-2": ("education","Cloud or desktop? It depends.","Honest comparison",
  "Desktop: fast and works offline at the counter, ideal for one location.\nCloud: access from anywhere and sync across devices.\n\nMany businesses want both. CodeLaksh ERP's desktop app works offline, and Growth adds cloud sync and the mobile app.", None, ERP, "Explore ERP", None),
"2026-11-04-1": ("industry-problem","Customers waiting just to place an order?","QR ordering for cafes and restaurants",
  "Waiting for a waiter just to place an order frustrates guests and slows tables.\n\nQR ordering, along with KOT, table management and reservations, is part of CodeLaksh ERP's Restaurant / Hotel Pro plan.", "mtab", ERP, "See the plan", None),
"2026-11-04-2": ("ai-trends","You already use AI. Here's where.","Everyday examples",
  "Spam filters, voice typing, product suggestions, maps that avoid traffic: AI is already in daily business life.\n\nThe next step is using it deliberately, for support, forecasting or automation.", None, SVC, "Explore AI solutions", None),
"2026-11-05-1": ("festival","Wishing you a bright and prosperous Diwali.","From all of us at CodeLaksh",
  "Happy Diwali from the CodeLaksh team.\n\nMay the year ahead bring growth to your business and joy to your family. Thank you for being part of our journey.", None, HOME, "Visit codelaksh.in", "Confirm Diwali date before approving"),
"2026-11-05-2": ("lead-cta","Your first invoice in 3 steps.","Free-trial walkthrough",
  "1. Start your 7-day free trial (Starter or Growth).\n2. Add your products and customers.\n3. Create an invoice, then print, download or share it.\n\nNeed help moving data from Tally, Vyapar or manual books? Ask about our migration add-on.", "inv", ERP, "Start your free trial", None),
"2026-11-06-1": ("brand-story","Thank you for being here.","From the CodeLaksh team",
  "Thank you for following CodeLaksh. We are building software for Indian businesses and we love hearing what you need next.\n\nWhat would you like to see in this feed: product demos, tips or behind the scenes?", None, HOME, "Follow us", None),
"2026-11-06-2": ("education","What are add-ons, and do you need them?","CodeLaksh ERP add-ons (excl. 18% GST)",
  "- Additional branch / outlet: Rs. 499 per month\n- WhatsApp / SMS invoice and order alerts: Rs. 299 per month (500 credits)\n- Payment gateway setup: Rs. 999 one-time\n- Data migration and onboarding: Rs. 2,999 one-time\n- Priority AMC for Starter: Rs. 1,999 per year", "plan", ERP, "See pricing and add-ons", None),
"2026-11-07-1": ("workflow-compare","Three branches, three different reports.","Single view for multi-outlet owners",
  "Calling each branch for numbers makes it hard to see the whole business.\n\nCodeLaksh Enterprise offers unlimited branches, multi-org and multi-outlet management, custom roles and advanced reports. Plans start from Rs. 4,999 per month (excludes 18% GST).", "rep", ERP, "Talk to us about Enterprise", None),
"2026-11-07-2": ("lead-cta","What's the one thing slowing your business?","Tell us, we'll suggest a solution",
  "Over the last few weeks we shared billing tips, product walkthroughs and how we build software.\n\nIf one problem keeps slowing your business, tell us. We'll suggest the right solution, whether that's our ERP or something custom.", None, CON, "Contact CodeLaksh", None),
"2026-11-08-1": ("product-demo","Your CA asks for reports. Export in a click.","Reports with CSV export",
  "Sales, purchase, stock and tax reports, with CSV export for easy sharing and analysis.\n\nPart of CodeLaksh ERP.", "rep", ERP, "See reports", None),
"2026-11-08-2": ("faq","Who do I call when something breaks?","Support by plan",
  "Starter: email support.\nGrowth: email and chat support.\nRestaurant / Hotel Pro: priority support.\nEnterprise: dedicated support.\n\nHave a question before you buy? Reach out and we'll help.", None, CON, "Contact CodeLaksh", None),
"2026-11-09-1": ("showcase","Everything we build, in one list.","CodeLaksh services",
  "- AI chatbots\n- Machine learning\n- Web development\n- App development (iOS and Android)\n- Cloud solutions (AWS, Azure, GCP)\n- Digital marketing (SEO and social)\n\nPlus our own products: CodeLaksh ERP and Kidodom.", None, SVC, "Start a project", None),
"2026-11-09-2": ("lead-cta","Ready to try it on your own counter?","7-day free trial",
  "CodeLaksh ERP: GST-ready billing, inventory and accounting for Indian shops, restaurants and hotels. Starter and Growth include a 7-day free trial.\n\nHave questions first? Message us here or use the contact form on our site.", "dash", ERP, "Start your free trial", None),
}
